services:
  g2-mininet:
    image: openalto/g2-mininet
    build: g2-mininet/
    extra_hosts:
      - "sflow:127.0.0.1"
      # - "odl:127.0.0.1"
    volumes:
      - /lib/modules:/lib/modules
      - ../etc/g2-mininet:/etc/g2-mininet
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    entrypoint: /bin/bash
    command: "-c 'service openvswitch-switch start && tail -f /dev/null'"
  sflow:
    image: sflow/sflow-rt:latest
    network_mode: "service:g2-mininet"
    environment:
      - RTMEM=2G
  odl:
    image: openalto/odl:0.8.4
    build: odl/
    # network_mode: "service:g2-mininet"
    entrypoint: /bin/bash
    ports:
      - "8181:8181"
    command: "-c '/opt/opendaylight/bin/start && tail -f /dev/null'"
